# Generated by Django 4.2.3 on 2023-07-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=255)),
                ('model_number', models.CharField(max_length=255)),
                ('first_publication_date', models.DateField()),
                ('on_market_start_date', models.DateField()),
                ('power_on_mode_sdr', models.FloatField()),
                ('power_on_mode_hdr', models.FloatField()),
                ('screen_area', models.IntegerField()),
                ('energy_class', models.CharField(max_length=255)),
                ('energy_class_sdr', models.CharField(max_length=255)),
                ('energy_class_hdr', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'new_energyLibrary',
            },
        ),
    ]
